# These are supported funding model platforms

github: []
patreon: pegasusheavy
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
custom: ["https://www.patreon.com/c/pegasusheavy?vanity=user"]
