name: 🔒 Security Vulnerability
description: Report a security vulnerability (for non-critical issues only)
title: "[Security]: "
labels: ["security", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Security Notice
        
        **For critical security vulnerabilities, please DO NOT open a public issue.**
        
        Instead, please report critical vulnerabilities privately:
        - Email: security@pegasusheavy.com
        - Or use GitHub's private vulnerability reporting feature
        
        Only use this template for low-severity security issues that are safe to discuss publicly.

  - type: checkboxes
    id: checks
    attributes:
      label: Security Checklist
      options:
        - label: This is NOT a critical vulnerability that could be actively exploited
          required: true
        - label: I have not included any sensitive information (credentials, PII, etc.)
          required: true
        - label: I understand this issue will be publicly visible
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this vulnerability?
      options:
        - Low (minor security improvement)
        - Medium (potential security issue under specific conditions)
      # Note: High/Critical should be reported privately
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      options:
        - Authentication/Authorization
        - Encryption
        - Input Validation
        - Information Disclosure
        - Denial of Service
        - Configuration
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue.
      placeholder: |
        Describe the vulnerability and its potential impact...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be demonstrated?
      placeholder: |
        1. Configure the server with...
        2. Send a request to...
        3. Observe that...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to fix this?
      placeholder: This could be fixed by...

  - type: input
    id: version
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: "v0.1.0 and earlier"
